name: Deploy static content to GitHub Pages

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main
  # Trigger the workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write

concurrency:
  # Ensure only one deployment is running at a time for Pages
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: GitHub Pages
      url: ${{ steps.deploy-pages.outputs.url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build and deploy
        id: deploy-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          # Set the GitHub token for deployments
          token: ${{ secrets.GITHUB_TOKEN }}
          # Configure the directory to deploy (change as needed)
          source: ./dist # Adjust based on your build output
          # Configure the target branch (gh-pages in this case)
          branch: gh-pages
